CREATE TABLE IF NOT EXISTS "PhoneOtp" (
  "phone"     TEXT NOT NULL,
  "code"      TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PhoneOtp_pkey" PRIMARY KEY ("phone")
);
