ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "scheduledDate" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "scheduledTime" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "reminderSentAt" TIMESTAMP(3);
